import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montreal = localFont({
  src: [
    {
      path: './fonts/PPNeueMontreal-Regular.woff2',
      style: 'regular',
    },
    {
      path: './fonts/PPNeueMontreal-Bold.woff2',
      style: 'bold',
    },
    {
      path: './fonts/PPNeueMontreal-Medium.woff2',
      style: 'medium',
    },
    {
      path: './fonts/PPNeueMontreal-Light.woff2',
      style: 'light',
    },
    {
      path: './fonts/PPNeueMontreal-Thin.woff2',
      style: 'thin',
    },
    {
      path: './fonts/PPNeueMontreal-Italic.woff2',
      style: 'italic',
    },
  ]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montreal.className}>
      <body>{children}</body>
    </html>
  );
}